### ISSUE TITLE
#5 メンバーの削除 3pt → 1pt

### ISSUE THREAD

**Issue by tsubasa-nishikawa** [OJT-3G/random-grouping-app#1]
なぜなら、利用者はグループメンバーの削除を行いたいからだ。

### DoR
- #3  が満たされている

### DoD
- メンバー一覧の表に「削除」ボタンがおかれた列が表示される
- 削除したメンバーの名前がメンバー一覧に表示されなくなる

### どのように
1. メンバー一覧の表に「削除」列を作る
1. メンバー一覧の削除列の全要素に「削除」ボタンを置く
1. 削除ボタン横のメンバー名を削除ボタン押下時に変数に入れる
1. ダミーデータから3の値を削除する
    - JavaScriptのfilter関数を使用

**Comment by RustyNail** [comment]
@tsubasa-nishikawa  さん( cc : @rknakashima  さん)

バックログは規模なので、今Sprintとしては残り1ptということはしません。
3ptのままなので、完了したSprintではベロシティが上がり、完了しなかった(仕掛かり中)Sprintはベロシティが出ません。
そのため、バックログ分割をするというお話をちょこちょこさせていただいています。
