### ISSUE TITLE
#5 メンバーの追加 3pt

### ISSUE THREAD

**Issue by tsubasa-nishikawa** [OJT-3G/random-grouping-app#2]
なぜなら、利用者はグループメンバーの追加を行いたいからだ。

### DoR
- #3  が満たされている

### DoD
- 追加したメンバーの名前がメンバー一覧に表示される

### どのように
1. メンバーの一覧の下にテキストボックスを表示する
2. テキストボックスの横に追加ボタンを置く
3. テキストボックスに入力された文字を追加ボタン押下時に変数に入れる
    - 「enter」押下時にも同様の処理をする(POがほとんどマウスを使わないため、追加要望)
    - 必要に応じて追加ボタンとテキストボックスを非表示にする

5. すでに存在する名前が入力された場合は「すでに存在する名前です、別の名前を入力してください」や空白の場合は「名前を入力してください」と赤文字で表示する    - エラーメッセージは実装時に最適と判断できる場所に配置する
5. 文字数は文字が画面外にはみ出ないように最適な文字数を実装時に指定する
6. 入力内容をダミーデータに追加する

**Comment by tsubasa-nishikawa** [comment]
@rknakashima さん、お疲れ様です。
このissueの実装は問題なくできたのですが、グループ数が空白又は0の時にメンバー追加をすると以下のエラーが出てしまいます。

![Image](https://user-images.githubusercontent.com/110072048/203222388-ac146eed-9e01-48b5-a570-92f048bb371b.png)

このエラーの対応タイミングについてご相談したいのですが、以下の案1,案2のどちらの方が良いでしょうか？
案1,グループ数が不正のままメンバー追加をすることはないと割り切り、MVP実装後に別issueで対応
案2,今スプリントでの計画は達成できなくなるが今issueで対応

**Comment by rknakashima** [comment]
> このエラーの対応タイミングについてご相談したいのですが、以下の案1,案2のどちらの方が良いでしょうか？

エラーの解消にはかなり時間がかかり、対応すると今スプリントでの計画は達成できなくなってしまう見込みなのですね。
案1 は、グループ数に不正な値が入っている間はメンバーの追加が行われない という制約がつき、エラーは発生しない ということであっていますか？
そうであれば、案1 で進めてもらっていいです。
そうでない場合、エラーが発生してほしくはないので、エラーが発生する状況を防ぐ対応はこのIssue内でやってほしいです。

**Comment by tsubasa-nishikawa** [comment]
> 案1 は、グループ数に不正な値が入っている間はメンバーの追加が行われない という制約がつき、エラーは発生しない ということであっていますか？
エラーは発生するままの想定でした。エラー発生時にメンバー追加が出来ないようにします。
