### ISSUE TITLE
#34 メンバーリストの保存 3pt

### ISSUE THREAD

**Issue by rknakashima** [OJT-3G/random-grouping-app#4]
なぜなら、利用者はアプリを再度開いたときにメンバー追加・削除したものが保持されていてほしいからだ。

### DoR
- #51

### DoD
- メンバーリストの変更後、アプリを再度立ち上げた時、PCの再起動を行った時に変更後のメンバーが表示されている
  - 使用デバイス、ブラウザは[Wiki](https://github.com/OJT-3G/random-grouping-app/wiki/%E9%96%8B%E7%99%BA%E3%83%AB%E3%83%BC%E3%83%AB)を参照

### どのように
- #51の通りに実装する

**Comment by tsubasa-nishikawa** [comment]
ポイントを3ptとした理由は以下です

- 値をゲットするタイミングは明確でないが実装に時間はかからないと判断した
- 以下の実装が明確である
  - メンバーの追加や削除が行われメンバーリストに変更があったときにLocalStrageに値をセットする
  - 初期値はダミーデータをそのまま使用する

が明確であるのでこのポイントにした。

**Comment by tsubasa-nishikawa** [comment]
メンバーリストの保存の実装に3pt以上の時間がかかっている

要因
・メンバーリストの保存機能の実装後に予期してない動きをし、解決に時間がかかっている

**Comment by tsubasa-nishikawa** [comment]
上記コメントの理由により遅れていたが、解決した。
受入テスト中である。

**Comment by yk-nakamura** [comment]
👆コメントで進捗状況記載しているのわかりやすくていいですね！

**Comment by tsubasa-nishikawa** [comment]
プルリクエストでの指摘修正が終わった。
指摘修正後の動作確認が終わればマージできる。
