### ISSUE TITLE
#6 グループ分け結果を表示する 2pt

### ISSUE THREAD

**Issue by tsubasa-nishikawa** [OJT-3G/random-grouping-app#7]
### DoD
グループ分けされた結果をブラウザで閲覧することが出来る。

### 制約
グループ数は固定値で3とする

![Image](https://user-images.githubusercontent.com/110072048/196116053-759a956c-a356-491e-a5a3-1ba5362f3ec0.png)

**Comment by yk-nakamura** [comment]
@tsubasa-nishikawa cc. @rknakashima 
途中でissueを分割したと思うのですが、その経緯もコメントで残しておいてほしいです。
例：`作業内容が多すぎたため、入力したグループ数と連動させるのは別issueで対応する` など。
